---

on:
  push:
    branches:
      - '*'

name: Fix Code Style

jobs:
  cs-fix:
    permissions:
      contents: write
    uses: spiral/gh-actions/.github/workflows/cs-fix.yml@master
    with:
      php: '["8.4"]'
